ARG BASE_IMAGE=ibp-pgscalculator-base:latest

FROM $BASE_IMAGE

WORKDIR /pgscalculator

COPY assets ./assets
COPY bin ./bin
COPY CHANGELOG.md ./CHANGELOG.md
COPY conf ./conf
COPY docker ./docker
COPY docs ./docs
COPY lib ./lib
COPY main.nf ./main.nf
COPY modules ./modules
COPY nextflow.config ./nextflow.config
COPY pgscalculator.sh ./pgscalculator.sh
COPY README.md ./README.md
COPY scripts ./scripts
COPY tests ./tests
COPY VERSION ./VERSION

WORKDIR /home/nextflow

