ARG BASE_IMAGE=ibp-pgscalculator-base:latest

FROM $BASE_IMAGE

WORKDIR /pgscalculator

COPY assets ./assets
COPY bin ./bin
COPY CHANGELOG.md ./CHANGELOG.md
COPY conf ./conf
COPY config.template.yaml ./config.template.yaml
COPY docker ./docker
COPY docs ./docs
COPY pgscalculator.sh ./pgscalculator.sh
COPY README.md ./README.md
COPY scripts ./scripts
COPY tests ./tests
COPY VERSION ./VERSION

WORKDIR /home/pgsuser

